version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rmq/definitions.json:/etc/rabbitmq/definitions.json
volumes:
  rabbitmq_data:
    driver: local
