addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.4.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"  % "0.9.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"  % "2.0.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.4")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"    % "5.7.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "2.0.5")
